In [3]:
import numpy as np
def load_uncounters(filename, row_ids, col_ids):
    arr = np.array([[0]*len(col_ids)]*len(row_ids))

    file1 = open(filename,"r")
    texte = file1.readlines()

    lenTexte = len(texte)

    """ Also OK
            for i in range(lenTexte):
        x = ord(texte[i][0])-49
        y = ord(texte[i][2])-65
        arr[x][y] = int(texte[i][-2]) """

    for i in range(lenTexte):
        x = int(texte[i][0])
        y = ord(texte[i][2])-65
        arr[x-1][y] = int(texte[i][-2])

    arr2 = np.array(row_ids)
    arr3 = np.array(col_ids)

    return arr, arr2, arr3

a = [1,2,3,4,5,6,7]
b = ['A','B','C','D','E','F','G','H','I']
print(load_uncounters("test.txt", a, b)[0])
print(load_uncounters("test.txt", a, b)[1])
print(load_uncounters("test.txt", a, b)[2])

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 0 0]]


In [17]:
arr = np.array([[0]*5]*4)
print(arr)
arr[2][3]=22
print(arr)

arr.max()



[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0 22  0]
 [ 0  0  0  0  0]]


22

In [8]:
import numpy as np
def load_uncounters(filename, row_ids, col_ids):
    arr = np.array([[0]*len(col_ids)]*len(row_ids))

    file1 = open(filename,"r")
    texte = file1.readlines()

    lenTexte = len(texte)

    """ Also OK
            for i in range(lenTexte):
        x = ord(texte[i][0])-49
        y = ord(texte[i][2])-65
        arr[x][y] = int(texte[i][-2]) """

    for i in range(lenTexte):
        x = int(texte[i][0])
        y = ord(texte[i][2])-65
        arr[x-1][y] = int(texte[i][-2])

    arr2 = np.array(row_ids)
    arr3 = np.array(col_ids)

    arrOdd = arr[1::2]

    arrCases = np.where(arr != 0)

    sumCol = np.sum(arr, axis = 0)
    max = sumCol.max()
    maxPos = np.where(sumCol == max)


    return arr, arr2, arr3, arr.max(), np.sum(arrOdd),len(arrCases[0]), b[maxPos[0][0]]

a = [1,2,3,4,5,6,7]
b = ['A','B','C','D','E','F','G','H','I']
print(load_uncounters("test.txt", a, b)[0])
print(load_uncounters("test.txt", a, b)[1])
print(load_uncounters("test.txt", a, b)[2])
print(load_uncounters("test.txt", a, b)[3])
print(load_uncounters("test.txt", a, b)[4])
print(load_uncounters("test.txt", a, b)[5])
print(load_uncounters("test.txt", a, b)[6])
x = load_uncounters("test.txt", a, b)
print(x[0], "\n", x[1], "\n", x[2], "\n", x[3], "\n", x[4], "\n", x[5], "\n", x[6])

""" arrFinal = load_uncounters("test.txt", a, b)[0]

arrFinal.max()

arrOdd = arrFinal[1::2]
print(arrOdd)
print(np.sum(arrOdd))

arrCases = np.where(arrFinal != 0)
print(len(arrCases[0]))

sumCol = np.sum(arrFinal, axis = 0)
print(sumCol)
max = sumCol.max()
print(max)
maxPos = np.where(sumCol == max)
print(maxPos[0][0])

print(b[maxPos[0][0]]) """

[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 3 1 0 0 4 0]
 [0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]]
[1 2 3 4 5 6 7]
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I']
4
13
7
H
[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 3 1 0 0 4 0]
 [0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]] 
 [1 2 3 4 5 6 7] 
 ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I'] 
 4 
 13 
 7 
 H


' arrFinal = load_uncounters("test.txt", a, b)[0]\n\narrFinal.max()\n\narrOdd = arrFinal[1::2]\nprint(arrOdd)\nprint(np.sum(arrOdd))\n\narrCases = np.where(arrFinal != 0)\nprint(len(arrCases[0]))\n\nsumCol = np.sum(arrFinal, axis = 0)\nprint(sumCol)\nmax = sumCol.max()\nprint(max)\nmaxPos = np.where(sumCol == max)\nprint(maxPos[0][0])\n\nprint(b[maxPos[0][0]]) '