In [23]:
import numpy as np
import csv
import pandas as pd

with open("Training.csv", 'r') as file:
    data = csv.reader(file)
    mylist = list(data)
    print(mylist)

    arr1 = np.array(mylist[0][1::]) 
    print(arr1)

    arr2 = np.array([""]*(len(mylist)-1),dtype='object')
    for i in range(1,len(mylist)-1):
        arr2[i] = mylist[2][0]
    print(arr2)

    x = np.loadtxt('Training.csv',usecols=range(1,6), skiprows=1, delimiter=',', dtype='int')
    print(x)

    print(np.argwhere(np.sum(x,axis=1)==0))
    a = np.argwhere(np.sum(x,axis=1)==0)
    b =[0]
    for i in range(len(a)):
        b.append(a[i][0]+1)
    print(b)

    df = pd.read_csv('Training.csv', skiprows=b, usecols=range(1,6))
    print(df)




[['Time Slot', 'Free weights', 'Pull-up bar', 'Bench press', 'Ab crunch', 'Cross Trainer'], ['T6-8', '0', '0', '0', '0', '0'], ['T8-10', '4', '3', '5', '8', '14'], ['T10-12', '3', '1', '2', '2', '12'], ['T12-14', '1', '2', '4', '1', '8'], ['T14-16', '0', '0', '0', '0', '0'], ['T16-18', '1', '2', '4', '5', '16'], ['T18-20', '3', '4', '5', '8', '10'], ['T20-22', '4', '5', '2', '6', '20'], ['T22-24', '0', '0', '0', '0', '0']]
['Free weights' 'Pull-up bar' 'Bench press' 'Ab crunch' 'Cross Trainer']
['' 'T8-10' 'T8-10' 'T8-10' 'T8-10' 'T8-10' 'T8-10' 'T8-10' 'T8-10']
[[ 0  0  0  0  0]
 [ 4  3  5  8 14]
 [ 3  1  2  2 12]
 [ 1  2  4  1  8]
 [ 0  0  0  0  0]
 [ 1  2  4  5 16]
 [ 3  4  5  8 10]
 [ 4  5  2  6 20]
 [ 0  0  0  0  0]]
[[0]
 [4]
 [8]]
[0, 1, 5, 9]
   4  3  5  8  14
0  3  1  2  2  12
1  1  2  4  1   8
2  1  2  4  5  16
3  3  4  5  8  10
4  4  5  2  6  20
['4', '3', '5', '8', '14']
