In [103]:
import numpy as np

file1 = open("test.txt","r")
texte = file1.readlines()
print(texte)
print(texte[0][-2])
print(type(texte[0][-2]))
x = int(texte[0][-2])
print(texte[0][-2])
print(type(x))
print(ord(texte[0][2]))

lenTexte = len(texte)
print(x)


['2 B 1\n', '2 F 2\n', '4 D 3\n', '4 E 1\n', '4 H 4\n', '6 B 2\n', '7 G 1\n']
1
<class 'str'>
1
<class 'int'>
66
1


In [125]:
import numpy as np
def load_uncounters(filename, row_ids, col_ids):
    arr = np.array([[0]*len(col_ids)]*len(row_ids))

    file1 = open(filename,"r")
    texte = file1.readlines()

    lenTexte = len(texte)

    """ Also OK
            for i in range(lenTexte):
        x = ord(texte[i][0])-49
        y = ord(texte[i][2])-65
        arr[x][y] = int(texte[i][-2]) """

    for i in range(lenTexte):
        x = int(texte[i][0])
        y = ord(texte[i][2])-65
        arr[x-1][y] = int(texte[i][-2])

    arr2 = np.array(row_ids)
    arr3 = np.array(col_ids)

    return arr, arr2, arr3

a = [1,2,3,4,5,6,7]
b = ['A','B','C','D','E','F','G','H','I']
print(load_uncounters("test.txt", a, b)[0])
print(load_uncounters("test.txt", a, b)[1])
print(load_uncounters("test.txt", a, b)[2])

arrFinal = load_uncounters("test.txt", a, b)[0]

arrFinal = load_uncounters("test.txt", a, b)[0]

arrFinal.max()

arrOdd = arrFinal[1::2]
print(arrOdd)
print(np.sum(arrOdd))

arrCases = np.where(arrFinal != 0)
print(len(arrCases[0]))

sumCol = np.sum(arrFinal, axis = 0)
print(sumCol)
max = sumCol.max()
print(max)
maxPos = np.where(sumCol == max)
print(maxPos[0][0])

print(b[maxPos[0][0]])




[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 3 1 0 0 4 0]
 [0 0 0 0 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0]]
[1 2 3 4 5 6 7]
['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I']
[[0 1 0 0 0 2 0 0 0]
 [0 0 0 3 1 0 0 4 0]
 [0 2 0 0 0 0 0 0 0]]
13
7
[0 3 0 3 1 2 1 4 0]
4
7
H
